apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockube-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dockube
  template:
    metadata:
      labels:
        app: dockube
    spec:
      containers:
      - name: dockube
        image: rohittrathod/dockube:latest # Replace with your Docker image name
        ports:
        - containerPort: 80

