apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmapp
  template:
    metadata:
      labels:
        app: ibmapp
    spec:
      containers:
      - name: ibmapp-container
        image: rohittrathod/ibmproject:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "256Mi"  # Minimum memory required
            cpu: "500m"      # Minimum CPU required
          limits:
            memory: "512Mi"  # Maximum memory allowed
            cpu: "1"         # Maximum CPU allowed