apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmapp  # Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmapp  # App label
  template:
    metadata:
      labels:
        app: ibmapp  # App label
    spec:
      containers:
      - name: ibmapp-container  # Container name
        image: rohittrathod/ibm-project3:latest  # Docker Hub image
        ports:
        - containerPort: 3000  # Port that the container listens on
        resources:
          requests:
            cpu: "250m"  # Minimum CPU request
            memory: "512Mi"  # Minimum memory request
          limits:
            cpu: "500m"  # Maximum CPU limit
            memory: "1Gi"  # Maximum memory limit