apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmapp  # Deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmapp  # App label
  template:
    metadata:
      labels:
        app: ibmapp  # App label
    spec:
      containers:
      - name: ibmapp-container  # Container name
        image: rohittrathod/ibm-project:latest  # Docker Hub image
        ports:
        - containerPort: 3000  # Port that the container listens on
