apiVersion: apps/v1
kind: Deployment
metadata:
  name: ibmapp  # Changed to your desired deployment name
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ibmapp  # Changed to your desired app label
  template:
    metadata:
      labels:
        app: ibmapp  # Changed to your desired app label
    spec:
      containers:
      - name: ibmapp-container  # Changed to your desired container name
        image: rohittrathod/ibmproject:latest  # Change this to your Docker Hub image
        ports:
        - containerPort: 8080