apiVersion: v1
kind: Service
metadata:
  name: ibmapp-app-service  # Name of the service
spec:
  type: NodePort  # Expose the service on a NodePort
  selector:
    app: ibmapp  # This should match the label in your deployment
  ports:
    - protocol: TCP
      port: 8080  # Port that the service will expose
      targetPort: 8080  # Port on the container that the service will forward to